In [54]:
include("JuliRay.jl")

render (generic function with 1 method)

In [53]:
Base.@irrational ° 0.0174532925199432957692369076848861271344 (big(pi)/big(180))

function ℝ²ₜₒS²(p::Array{T,1}) where T<:Real
    if(length(p)≠2)
        error("No Point on ℝ²")
    end
    return [2p[1]/(1+p[1]^2+p[2]^2),2p[2]/(1+p[1]^2+p[2]^2),(-1+p[1]^2+p[2]^2)/(1+p[1]^2+p[2]^2)]
end

function ℝ²ₜₒS²(θ::Real,p::Array{T,1}) where T<:Real
    if(length(p)≠2)
        error("No Point on ℝ²")
    end
    c=[0,0,tan(θ)]
    r=1/cos(θ)
    P=p*cot(θ/2+π/4)
    return ℝ²ₜₒS²(P)*r+c
end

function ℝ³ₜₒS³(p::Array{T,1}) where T<:Real
    if(length(p)≠3)
        error("No Point on ℝ³")
    end
    return [2p[1]/(1+p[1]^2+p[2]^2+p[3]^2),2p[2]/(1+p[1]^2+p[2]^2+p[3]^2),2p[3]/(1+p[1]^2+p[2]^2+p[3]^2),(-1+p[1]^2+p[2]^2+p[3]^2)/(1+p[1]^2+p[2]^2+p[3]^2)]
end

function ℝ³ₜₒS³(θ::Real,p::Array{T,1}) where T<:Real
    if(length(p)≠3)
        error("No Point on ℝ³")
    end
    c=[0,0,0,tan(θ)]
    r=1/cos(θ)
    P=p*cot(θ/2+π/4)
    return ℝ³ₜₒS³(P)*r+c
end

function S²ₜₒℝ²(q::Array{T,1}) where T<:Real
    if(length(q)≠3)
        error("No Point on S²")
    end
    return [q[1]/(1-q[3]),q[2]/(1-q[3])]
end

function S²ₜₒℝ²(θ::Real,q::Array{T,1}) where T<:Real
    if(length(q)≠3)
        error("No Point on S²")
    end
    c=[0,0,tan(θ)]
    r=1/cos(θ)
    return S²ₜₒℝ²((q-c)/r)*tan(θ/2+π/4)
end

function S³ₜₒℝ³(q::Array{T,1}) where T<:Real
    if(length(q)≠4)
        error("No Point on S³")
    end
    return [q[1]/(1-q[4]),q[2]/(1-q[4]),q[3]/(1-q[4])]
end

function S³ₜₒℝ³(θ::Real,q::Array{T,1}) where T<:Real
    if(length(q)≠4)
        error("No Point on S³")
    end
    c=[0,0,0,tan(θ)]
    r=1/cos(θ)
    return S³ₜₒℝ³((q-c)/r)*tan(θ/2+π/4)
end

S³ₜₒℝ³ (generic function with 2 methods)

In [4]:
using LinearAlgebra

In [177]:
struct VERTEX
    v :: Int
end

struct EDGE
    e :: Array{VERTEX,1}
    EDGE(e)=
    if(length(e)<2)
        error("hoge")
    elseif(e[1]==e[2])
        error("fuga")
    else
        new(collect(Set(e)))
    end
end

function istouching(edge1::EDGE,edge2::EDGE)
    return length(Set(edge1.e) ∩ Set(edge2.e)) == 1
end

# struct FACE
#     f :: Array{EDGE,1}
#     FACE(f)=
#     (
#         if(length(f)<3)
#             error("hoge")
#         else
#         hoge=[istouching(edge1,edge2) for edge1 ∈ f, edge2 ∈ f];
#         println(hoge)
#             new(collect(Set(f)))
#         end
#     )
# end

struct FACE
    f :: Array{EDGE,1}
    FACE(f)=
    (
        V=union(((edge->edge.e).(f))...);
        println(V);
#         println((edge->edge.e).(f));
        println((edge->edge.e).(f));
        global fffff=[[(edge->edge.e).(f)...] for v ∈ V] ;
        if(true)
            new(collect(Set(f)))
        end
    )
end

struct FACE
    f :: Array{EDGE,1}
    FACE(f)=
    (
            new(collect(Set(f)))
    )
end

In [173]:
f=[EDGE([VERTEX(1),VERTEX(2)]),EDGE([VERTEX(2),VERTEX(3)]),EDGE([VERTEX(3),VERTEX(1)])]
union(((edge->edge.e).(f))...)

3-element Array{VERTEX,1}:
 VERTEX(2)
 VERTEX(1)
 VERTEX(3)

In [180]:
hoge=FACE([EDGE([VERTEX(1),VERTEX(2)]),EDGE([VERTEX(2),VERTEX(3)]),EDGE([VERTEX(3),VERTEX(1)])])

FACE(EDGE[EDGE(VERTEX[VERTEX(2), VERTEX(1)]), EDGE(VERTEX[VERTEX(1), VERTEX(3)]), EDGE(VERTEX[VERTEX(2), VERTEX(3)])])

In [1]:
abstract type POLYTOPE end

import Base.==
function ==(poly1::POLYTOPE,poly2::POLYTOPE)
    return translate(poly1)==translate(poly2)
end

struct VERTEX <: POLYTOPE
    v :: Int
end
struct EDGE <: POLYTOPE
    e :: Array{VERTEX,1}
    EDGE(e)=
    if(true)
        new(collect(Set(e)))
    end
end
struct FACE <: POLYTOPE
    f :: Array{EDGE,1}
    FACE(f)=
    if(true)
        new(collect(Set(f)))
    end
end
struct CELL <: POLYTOPE
    c :: Array{FACE,1}
    CELL(c)=
    if(true)
        new(collect(Set(c)))
    end
end

function translate(vertex::VERTEX)
    return vertex.v
end
function translate(edge::EDGE)
    return translate.(edge.e)
end
function translate(face::FACE)
    return translate.(face.f)
end
function translate(cell::CELL)
    return translate.(cell.c)
end

function translate(v::Int)
    return VERTEX(v)
end
function translate(e::Array{Int,1})
    return EDGE(translate.(e))
end
function translate(f::Array{Array{Int,1},1})
    return FACE(translate.(f))
end
function translate(c::Array{Array{Array{Int,1},1},1})
    return CELL(translate.(c))
end

translate (generic function with 8 methods)

In [19]:
# triangle
F=FACE(EDGE[EDGE(VERTEX[VERTEX(1), VERTEX(2)]), EDGE(VERTEX[VERTEX(2), VERTEX(3)]), EDGE(VERTEX[VERTEX(3), VERTEX(1)])])

FACE(EDGE[EDGE(VERTEX[VERTEX(2), VERTEX(3)]), EDGE(VERTEX[VERTEX(1), VERTEX(3)]), EDGE(VERTEX[VERTEX(2), VERTEX(1)])])

In [22]:
f=F.f

3-element Array{EDGE,1}:
 EDGE(VERTEX[VERTEX(2), VERTEX(3)])
 EDGE(VERTEX[VERTEX(1), VERTEX(3)])
 EDGE(VERTEX[VERTEX(2), VERTEX(1)])

In [52]:
edges=translate.(f)
vertices=collect(Set(vcat(edges...)))
*([sum(v ∈ e for e ∈ edges)==2 for v ∈ vertices]...)

true

In [48]:
&&(true,true)

LoadError: syntax: invalid identifier name "&&"

In [49]:
true && true

true

In [50]:
true*true

true

In [51]:
false + true

1

In [231]:
FACE(f)

FACE(EDGE[EDGE(VERTEX[VERTEX(2), VERTEX(1)]), EDGE(VERTEX[VERTEX(1), VERTEX(3)]), EDGE(VERTEX[VERTEX(2), VERTEX(3)])])

In [232]:
translate(FACE(f))

3-element Array{Array{Int64,1},1}:
 [2, 1]
 [1, 3]
 [2, 3]

In [237]:
translate.(f)

3-element Array{Array{Int64,1},1}:
 [2, 1]
 [1, 3]
 [2, 3]

In [234]:
translate(translate(FACE(f)))

FACE(EDGE[EDGE(VERTEX[VERTEX(2), VERTEX(3)]), EDGE(VERTEX[VERTEX(2), VERTEX(1)]), EDGE(VERTEX[VERTEX(1), VERTEX(3)])])

In [236]:
[1,[2,3],3]==[1,[2,3],3]

true

In [213]:
translate([1,2])

EDGE(VERTEX[VERTEX(2), VERTEX(1)])

In [203]:
translate(EDGE([VERTEX(1),VERTEX(2)]))

2-element Array{Int64,1}:
 2
 1

2-element Array{Array{Int64,1},1}:
 [1, 2]
 [1, 2]

In [ ]:
coordinate=[[]]

In [175]:
fffff

3-element Array{Array{Array{VERTEX,1},1},1}:
 [[VERTEX(2), VERTEX(1)], [VERTEX(2), VERTEX(3)], [VERTEX(1), VERTEX(3)]]
 [[VERTEX(2), VERTEX(1)], [VERTEX(2), VERTEX(3)], [VERTEX(1), VERTEX(3)]]
 [[VERTEX(2), VERTEX(1)], [VERTEX(2), VERTEX(3)], [VERTEX(1), VERTEX(3)]]

In [158]:
VERTEX[VERTEX(2), VERTEX(1), VERTEX(3)]

3-element Array{VERTEX,1}:
 VERTEX(2)
 VERTEX(1)
 VERTEX(3)

In [159]:
Array{VERTEX,1}[[VERTEX(2), VERTEX(1)], [VERTEX(2), VERTEX(3)], [VERTEX(1), VERTEX(3)]]

3-element Array{Array{VERTEX,1},1}:
 [VERTEX(2), VERTEX(1)]
 [VERTEX(2), VERTEX(3)]
 [VERTEX(1), VERTEX(3)]

In [101]:
Array{VERTEX,1}[[VERTEX(2), VERTEX(1)], [VERTEX(2), VERTEX(3)], [VERTEX(1), VERTEX(3)]]

3-element Array{Array{VERTEX,1},1}:
 [VERTEX(2), VERTEX(1)]
 [VERTEX(2), VERTEX(3)]
 [VERTEX(1), VERTEX(3)]

In [74]:
Set(1:20)

Set([12, 4, 18, 2, 3, 16, 11, 5, 20, 7, 9, 13, 10, 14, 19, 17, 8, 15, 6, 1])

In [67]:
Set([1,2,5,4,3,2])

Set([4, 2, 3, 5, 1])

In [68]:
Set([1,2,4,3,3,5])

Set([4, 2, 3, 5, 1])

In [29]:
istouching(EDGE([VERTEX(1),VERTEX(2)]),EDGE([VERTEX(3),VERTEX(5)]))

false

In [42]:
Set([1, 2, 3, "Some text"])∩Set([1, 2, "Some text"])

Set(Any["Some text", 2, 1])

In [20]:
length(Set([1, 3, 2,3, "Some text"]))

4

In [32]:
typeof(Set)

UnionAll

In [37]:
@less Set([1])

# This file is a part of Julia. License is MIT: https://julialang.org/license

struct Set{T} <: AbstractSet{T}
    dict::Dict{T,Nothing}

    Set{T}() where {T} = new(Dict{T,Nothing}())
    Set{T}(s::Set{T}) where {T} = new(Dict{T,Nothing}(s.dict))
end

Set{T}(itr) where {T} = union!(Set{T}(), itr)
Set() = Set{Any}()


"""
    Set([itr])

Construct a [`Set`](@ref) of the values generated by the given iterable object, or an
empty set. Should be used instead of [`BitSet`](@ref) for sparse integer sets, or
for sets of arbitrary objects.
"""
Set(itr) = _Set(itr, IteratorEltype(itr))

_Set(itr, ::HasEltype) = Set{eltype(itr)}(itr)

function _Set(itr, ::EltypeUnknown)
    T = @default_eltype(itr)
    (isconcretetype(T) || T === Union{}) || return grow_to!(Set{T}(), itr)
    return Set{T}(itr)
end

empty(s::AbstractSet{T}, ::Type{U}=T) where {T,U} = Set{U}()

# return an empty set with eltype T, which is mutable (can be grown)
# by default, a Set is returned
emptymutable(s::AbstractSet{T}, ::

# Examples
```jldoctest
julia> replace!([1, 2, 1, 3], 1=>0, 2=>4, count=2)
4-element Array{Int64,1}:
 0
 4
 1
 3

julia> replace!(Set([1, 2, 3]), 1=>0)
Set([0, 2, 3])
```
"""
replace!(A, old_new::Pair...; count::Integer=typemax(Int)) =
    replace_pairs!(A, A, check_count(count), old_new)

function replace_pairs!(res, A, count::Int, old_new::Tuple{Vararg{Pair}})
    @inline function new(x)
        for o_n in old_new
            isequal(first(o_n), x) && return last(o_n)
        end
        return x # no replace
    end
    _replace!(new, res, A, count)
end

"""
    replace!(new::Function, A; [count::Integer])

Replace each element `x` in collection `A` by `new(x)`.
If `count` is specified, then replace at most `count` values in total
(replacements being defined as `new(x) !== x`).

# Examples
```jldoctest
julia> replace!(x -> isodd(x) ? 2x : x, [1, 2, 3, 4])
4-element Array{Int64,1}:
 2
 2
 6
 4

julia> replace!(Dict(1=>2, 3=>4)) do kv
           first(kv) < 3 ? first(kv)=>3 : kv
     

In [41]:
Set([1, 3, 2,3, "Some text"]).dict

Dict{Any,Nothing} with 4 entries:
  "Some text" => nothing
  2           => nothing
  3           => nothing
  1           => nothing

In [3]:
struct FACE
    f :: Array{EDGE,1}
end

In [4]:
struct CELL
    c :: Array{FACE,1}
end

In [5]:
v₁=VERTEX([0,0,0])
v₂=VERTEX([1,0,0])
v₃=VERTEX([0,1,0])
v₄=VERTEX([0,0,2])
EDGE([v₁,v₂])
EDGE([v₂,v₃])

EDGE(VERTEX[VERTEX([1.0, 0.0, 0.0]), VERTEX([0.0, 1.0, 0.0])])

In [3]:
struct Polyhedron
    vertices :: Array{Array{Float64,1},1}
    V :: Array{Int,1}
    E :: Array{Array{Int,1},1}
    F :: Array{Array{Int,1},1}
end

In [4]:
tet=Polyhedron([[0.0,0.0,0.0],[1.0,0.0,0.0],[0.0,1.0,0.0],[0.0,0.0,1.0]],[1,2,3,4],[[1,2],[1,3],[1,4],[2,3],[2,4],[3,4]],[[2,3,4],[1,3,4],[1,2,4],[1,2,3]])

Polyhedron(Array{Float64,1}[[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]], [1, 2, 3, 4], Array{Int64,1}[[1, 2], [1, 3], [1, 4], [2, 3], [2, 4], [3, 4]], Array{Int64,1}[[2, 3, 4], [1, 3, 4], [1, 2, 4], [1, 2, 3]])

In [7]:
function P2O(polyhedron::Polyhedron)
    vertices=polyhedron.vertices[polyhedron.V]
    print(vertices)
    objV=csgUnion((p->Sphere(p,0.03)).(vertices))
    objE=csgUnion()
    return csgUnion(objV)
end

P2O (generic function with 1 method)

In [6]:
render(P2O(tet),camera=LngLatCamera(lng=30°,lat=30°,pers=0.2,zoom=0.2,width=640,height=360),name="test")

Array{Float64,1}[[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]

povray: cannot open the user configuration file /home/hyrodium/.povray/3.7/povray.conf: No such file or directory
Persistence of Vision(tm) Ray Tracer Version 3.7.0.8.unofficial (g++ 8.2.1 @
 x86_64-pc-linux-gnu)
This is an unofficial version compiled by:
 Arch Linux
 The POV-Ray Team is not responsible for supporting this version.

POV-Ray is based on DKBTrace 2.12 by David K. Buck & Aaron A. Collins
Copyright 1991-2013 Persistence of Vision Raytracer Pty. Ltd.

Primary POV-Ray 3.7 Architects/Developers: (Alphabetically)
  Chris Cason         Thorsten Froehlich  Christoph Lipka   

With Assistance From: (Alphabetically)
  Nicolas Calimet     Jerome Grimbert     James Holsenback    Christoph Hormann 
  Nathan Kopp         Juha Nieminen     

Past Contributors: (Alphabetically)
  Steve Anger         Eric Barish         Dieter Bayer        David K. Buck     
  Nicolas Calimet     Chris Cason         Aaron A. Collins    Chris Dailey      
  Steve Demlow        Andreas Dilger      Alexande

Process(`povray test.pov`, ProcessExited(0))

In [ ]:
Array{}

In [ ]:
function POLYGON(vertices;r1=1.0,r2=0.05,r3=0.025)
    n=length(vertices)
    V=rgbColor(csgUnion((p->Sphere(p,r2)).(vertices)),RGB(0.1,0.1,0.1))
    E=rgbColor(csgUnion([Cylinder(vertices[i],vertices[mod(i,n)+1],r3) for i in 1:n]),RGB(0.1,0.1,0.1))
    F=rgbftColor(Polygon(vertices),RGB(0.5,1,1),FT(0.1,0.1))
    return csgUnion(V,E,F)
end

function POLYGON2(vertices,O,R;r1=1.0,r2=0.05,r3=0.025)
    n=length(vertices)
    C=O+R*normalize(+(vertices...)/n-O)
    V=rgbColor(csgUnion((p->Sphere(p,r2)).(vertices)),RGB(0.1,0.1,0.1))
    E=rgbColor(csgUnion([Arc(vertices[i],O+R*normalize((vertices[i]+vertices[mod(i,n)+1])/2-O),vertices[mod(i,n)+1],r3) for i in 1:n]),RGB(0.1,0.1,0.1))
    if(R<10^2)
        F=csgClip(
            rgbftColor(
                Sphere(O,R),RGB(1,0.5,1),FT(0.1,0.1)
            ),
            csgIntersection(
                [
                    (v=NormalVector(O,vertices[i],vertices[mod(i,n)+1]);s=sign(dot(v,C-O));Cylinder(O,O+s*R*v,R))
                for i ∈ 1:n]
            )
        )
    else
        F=rgbftColor(Polygon(vertices),RGB(1,0.5,1),FT(0.1,0.1))
    end
    return csgUnion(V,E,F)
end

function Mirror(q,p1,p2,p3)
    e₃=NormalVector(p1,p2,p3)
    e₁=OrthogonalVector(e₃)
    e₂=cross(e₃,e₁)
    A=hcat(e₁,e₂,e₃)*transpose(hcat(e₁,e₂,-e₃))
    fixedpoint=(p1+p2+p3)/3
    b=fixedpoint-A*fixedpoint
    return A*q+b
end

function Put(F,i,O)
    p1=O
    n=length(F)
    p2,p3=F[mod(i-1,n)+1],F[mod(i,n)+1]
    return (p->Mirror(p,p1,p2,p3)).(F)
end

function f(x)
    ifelse(x>0,exp(-1/x),0)
end
function g(x)
    f(2x/√3)/(f(2x/√3)+f(2/√3-2x/√3))
end
function Smooth(a,b,x)
    g((x-a)/(b-a))
end

In [ ]:
## Tetrahedron

h=1/3 # 単位球面に内接させた際の内接球半径
n=3 # n角形
m=4 # m面体
M=60 # アニメーションの刻み数

r1=√(1-h^2) # n角形の外接円半径
for i ∈ 1:M
    θ=(1-Smooth(0,1,2(i-1)/M)+Smooth(1,2,2(i-1)/M))*π/2 # パラメータθは0→1→0の順で滑らかに変化
    R=1/cos(θ)
    O=[0,0,tan(θ)]
    N=O+[0,0,R]
    H=O-[0,0,√(R^2-r1^2)]

    F=[[[r1*cos(2π*i/n),r1*sin(2π*i/n),0.0]+H for i in 1:n] for i ∈ 1:m] # 最初のn角形の頂点
    F[2]=Put(F[1],1,O) # 以下はn角形を付け加える操作
    F[3]=Put(F[2],2,O)
    F[4]=Put(F[2],3,O)

    object=csgUnion([POLYGON2(F[i],O,R,r2=0.03,r3=0.01) for i ∈ 1:m]) # 頂点座標をもとにオブジェクトを生成
    render(csgUnion(object),camera=LngLatCamera(lng=30°,lat=30°,pers=0.2,zoom=0.2,width=640,height=360),name="Ns"*string(m),index=i)
end

In [ ]:
## Cube

h=1/√3 # 単位球面に内接させた際の内接球半径
n=4 # n角形
m=6 # m面体
M=60 # アニメーションの刻み数

r1=√(1-h^2) # n角形の外接円半径
for i ∈ 1:M
    θ=(1-Smooth(0,1,2(i-1)/M)+Smooth(1,2,2(i-1)/M))*π/2 # パラメータθは0→1→0の順で滑らかに変化
    R=1/cos(θ)
    O=[0,0,tan(θ)]
    N=O+[0,0,R]
    H=O-[0,0,√(R^2-r1^2)]

    F=[[[r1*cos(2π*i/n),r1*sin(2π*i/n),0.0]+H for i in 1:n] for i ∈ 1:m] # 最初のn角形の頂点
    F[2]=Put(F[1],1,O) # 以下はn角形を付け加える操作
    F[3]=Put(F[2],3,O)
    F[4]=Put(F[1],2,O)
    F[5]=Put(F[4],3,O)
    F[6]=Put(F[5],1,O)

    object=csgUnion([POLYGON2(F[i],O,R,r2=0.03,r3=0.01) for i ∈ 1:m]) # 頂点座標をもとにオブジェクトを生成
    render(object,camera=LngLatCamera(lng=30°,lat=30°,pers=0.2,zoom=0.2,width=640,height=360),name="Ns"*string(m),index=i)
end

In [ ]:
## Octahedron

h=1/√3 # 単位球面に内接させた際の内接球半径
n=3 # n角形
m=8 # m面体
M=60 # アニメーションの刻み数

r1=√(1-h^2) # n角形の外接円半径
for i ∈ 1:M
    θ=(1-Smooth(0,1,2(i-1)/M)+Smooth(1,2,2(i-1)/M))*π/2 # パラメータθは0→1→0の順で滑らかに変化
    R=1/cos(θ)
    O=[0,0,tan(θ)]
    N=O+[0,0,R]
    H=O-[0,0,√(R^2-r1^2)]

    F=[[[r1*cos(2π*i/n),r1*sin(2π*i/n),0.0]+H for i in 1:n] for i ∈ 1:m] # 最初のn角形の頂点
    F[2]=Put(F[1],1,O) # 以下はn角形を付け加える操作
    F[3]=Put(F[2],3,O)
    F[4]=Put(F[3],2,O)
    F[5]=Put(F[4],3,O)
    F[6]=Put(F[1],2,O)
    F[7]=Put(F[6],3,O)
    F[8]=Put(F[7],2,O)

    object=csgUnion([POLYGON2(F[i],O,R,r2=0.03,r3=0.01) for i ∈ 1:m]) # 頂点座標をもとにオブジェクトを生成
    render(object,camera=LngLatCamera(lng=30°,lat=30°,pers=0.2,zoom=0.2,width=640,height=360),name="Ns"*string(m),index=i)
end

In [ ]:
## Dodecahedron

φ=2cos(π/5)
ξ=2sin(π/5)

h=φ/(√3*ξ) # 単位球面に内接させた際の内接球半径
n=5 # n角形
m=12 # m面体
M=60 # アニメーションの刻み数

r1=√(1-h^2) # n角形の外接円半径
for i ∈ 1:M
    θ=(1-Smooth(0,1,2(i-1)/M)+Smooth(1,2,2(i-1)/M))*π/2 # パラメータθは0→1→0の順で滑らかに変化
    R=1/cos(θ)
    O=[0,0,tan(θ)]
    N=O+[0,0,R]
    H=O-[0,0,√(R^2-r1^2)]

    F=[[[r1*cos(2π*i/n),r1*sin(2π*i/n),0.0]+H for i in 1:n] for i ∈ 1:m] # 最初のn角形の頂点
    F[2]=Put(F[1],4,O) # 以下はn角形を付け加える操作
    F[3]=Put(F[2],1,O)
    F[4]=Put(F[2],2,O)
    F[5]=Put(F[2],3,O)
    F[6]=Put(F[2],5,O)
    F[7]=Put(F[1],2,O)
    F[8]=Put(F[7],5,O)
    F[9]=Put(F[8],1,O)
    F[10]=Put(F[8],2,O)
    F[11]=Put(F[8],3,O)
    F[12]=Put(F[8],4,O)

    object=csgUnion([POLYGON2(F[i],O,R,r2=0.03,r3=0.01) for i ∈ 1:m]) # 頂点座標をもとにオブジェクトを生成
    render(object,camera=LngLatCamera(lng=30°,lat=30°,pers=0.2,zoom=0.2,width=640,height=360),name="Ns"*string(m),index=i)
end

In [ ]:
## Icosahedron

φ=2cos(π/5)
ξ=2sin(π/5)

h=φ/(√3*ξ) # 単位球面に内接させた際の内接球半径
n=3 # n角形
m=20 # m面体
M=60 # アニメーションの刻み数

r1=√(1-h^2) # n角形の外接円半径
for i ∈ 1:M
    θ=(1-Smooth(0,1,2(i-1)/M)+Smooth(1,2,2(i-1)/M))*π/2 # パラメータθは0→1→0の順で滑らかに変化
    R=1/cos(θ)
    O=[0,0,tan(θ)]
    N=O+[0,0,R]
    H=O-[0,0,√(R^2-r1^2)]

    F=[[[r1*cos(2π*i/n),r1*sin(2π*i/n),0.0]+H for i in 1:n] for i ∈ 1:m] # 最初のn角形の頂点
    F[2]=Put(F[1],1,O) # 以下はn角形を付け加える操作
    F[3]=Put(F[2],3,O)
    F[4]=Put(F[3],2,O)
    F[5]=Put(F[4],1,O)
    F[6]=Put(F[5],3,O)
    F[7]=Put(F[1],2,O)
    F[8]=Put(F[7],3,O)
    F[9]=Put(F[8],1,O)
    F[10]=Put(F[9],2,O)
    F[11]=Put(F[1],3,O)
    F[12]=Put(F[2],2,O)
    F[13]=Put(F[3],1,O)
    F[14]=Put(F[4],3,O)
    F[15]=Put(F[5],2,O)
    F[16]=Put(F[6],1,O)
    F[17]=Put(F[7],1,O)
    F[18]=Put(F[8],2,O)
    F[19]=Put(F[9],3,O)
    F[20]=Put(F[10],1,O)

    object=csgUnion([POLYGON2(F[i],O,R,r2=0.03,r3=0.01) for i ∈ 1:m]) # 頂点座標をもとにオブジェクトを生成
    render(object,camera=LngLatCamera(lng=30°,lat=30°,pers=0.2,zoom=0.2,width=640,height=360),name="Ns"*string(m),index=i)
end